---
title: "BO-EMEWS example"
output:
  html_document:
    df_print: paged
---

```{r}
library(lhs)
library(laGP)
library(mvtnorm)
```


## Sample simulation function

```{r}

foo <- function(X)
 {
  if(is.null(nrow(X))) X <- matrix(X, nrow=1)
  m <- 8.6928
  s <- 2.4269
  x1 <- 4*X[,1] - 2
  x2 <- 4*X[,2] - 2
  a <- 1 + (x1 + x2 + 1)^2 * 
    (19 - 14*x1 + 3*x1^2 - 14*x2 + 6*x1*x2 + 3*x2^2)
  b <- 30 + (2*x1 - 3*x2)^2 * 
    (18 - 32*x1 + 12*x1^2 + 48*x2 - 36*x1*x2 + 27*x2^2)
  f <- log(a*b)
  f <- (f - m)/s + rnorm(1, sd = 0.1)
  return(f)
 }
```

## Utility function

```{r}

 # a multivariate normal random vector generator
rmultnorm <- function(n,mu,sigma){
   # returns n rows of multinormal mu,sigma random vectors
   # ie: returns a n x length(mu) matrix
  p <- length(mu)
  z <- matrix(rnorm(n * p),nrow=n)
  ch <- chol(sigma,pivot=TRUE)
  piv <- attr(ch,"pivot")
  zz <- (z%*%ch)
  zzz <- 0*zz
  zzz[,piv] <- zz
  zzz + matrix(mu,nrow=n,ncol=p,byrow=TRUE)
}

#' Thompson sampling batch BO
#'
#' @param Xgrid search grid, given by a matrix of size (N x nparam) where N is the number of unique #' design points
#' @param init_id index such that the initial simulations are run at Xgrid[init_id, ]
#' @param noptiter size of TS optimization loop
#' @param nsamp number of samples/new simulations to try at each iterations
#' @param sim_func simulation functions
#' @param verb if output should be printed
#' @param ... 
#'
#' @return a list of best objective value, simulation input, output

TS_opt <- function(Xgrid,
                   init_id,
                   noptiter,
                   nsamp,
                   sim_func,
                   verb = TRUE,
                   ...){
  
  m <- ncol(Xgrid)
  
  ## for book-keeping
  nparam <- ncol(Xgrid)
  f_best <- rep(NA, noptiter)
  new_x <- new_y <- idlist <- list()
  
  # initial evaluations
  XX <- Xgrid[init_id, ]
  YY <- c()
  for (ii in 1:length(init_id)){
    YY[ii] <- sim_func(XX[ii, ])
  }
  
  ## iteration 1
  f_best[1] <- min(YY)
  
  if(verb)  cat(">> iter = ", 1, "| current best value = ", 
                f_best[1], "at x1 = ", XX[which.min(YY), 1], ", x2 = ", XX[which.min(YY), 2], "\n")
  
  ## fit GP
  da <- darg(list(mle=TRUE, max=0.5), randomLHS(1000, m))
  gpi <- newGPsep(XX, YY, d=da$start, g=1e-6, dK=TRUE)
  mleGPsep(gpi, param="d", tmin=da$min, tmax=da$max, ab=da$ab)
  
  ## predict and conditional sample
  pred <- predGPsep(gpi, Xgrid, lite=F)
  tTS <- rmvnorm(nsamp, pred$mean, 1/2 * (pred$Sigma + t(pred$Sigma)))
  
  ## next best
  idlist[[1]] <- unique(apply(tTS, 1, which.min))
  new_x[[1]] <- Xgrid[idlist[[1]], ]
  new_y[[1]] <- sim_func(new_x[[1]])
  
  ## TS optimization loop
  for(iter_ in 2:noptiter){
    
    # data until (iter-1)
    YY <- c(YY, new_y[[iter_ - 1]])
    XX <- rbind(XX, new_x[[iter_ - 1]])
    f_best[iter_] <- min(YY)
    
    # f_best[iter] <- min(YY)
    if(verb) cat(">> iter = ", iter_, "| current best value = ", 
                f_best[iter_], "at x1 = ", XX[which.min(YY), 1], 
                ", x2 = ", XX[which.min(YY), 2], "\n")
    # if(verb) cat("iter = ", iter_, ", current best value = ", 
    #              f_best[iter], "at x = ", new_x[[iter]], "\n")
    
    # update GP
    updateGPsep(gpi, new_x[[iter_ - 1]], new_y[[iter_ - 1]])
    mleGPsep(gpi, param="d", tmin=da$min, tmax=da$max, ab=da$ab)
    
    ## predict and conditional sample
    pred <- predGPsep(gpi, Xgrid, lite=F)
    tTS <- rmvnorm(nsamp, pred$mean, 1/2 * (pred$Sigma + t(pred$Sigma)))
    
    ## next best
    idlist[[iter_]] <- unique(apply(tTS, 1, which.min))
    new_x[[iter_]] <- Xgrid[idlist[[iter_]], ]
    new_y[[iter_]] <- sim_func(new_x[[iter_]])
    
  }
  deleteGPsep(gpi)
  
  return(list(f_best = f_best, 
              new_x = new_x, 
              new_y = new_y))
  
}
```


## Run the optimization

Goal is to minimize `foo`.

```{r, eval=T, warning=FALSE}
set.seed(1)
N <- 1000
Xgrid <- randomLHS(N, 2)
res <- TS_opt(Xgrid = Xgrid,
              init_id = sample(N, 50),
              noptiter = 20,
              nsamp = 30,
              sim_func = foo)
```

