---
title: "BO-EMEWS example using DiceOptim"
output:
  html_document:
    df_print: paged
---

```{r}
library(lhs)
library(DiceOptim)
library(mvtnorm)
```

## Sample simulation function

```{r}

foo <- function(X)
 {
  # if(is.null(nrow(X))) X <- matrix(X, nrow=1)
  m <- 8.6928
  s <- 2.4269
  x1 <- 4*X[1] - 2
  x2 <- 4*X[2] - 2
  a <- 1 + (x1 + x2 + 1)^2 * 
    (19 - 14*x1 + 3*x1^2 - 14*x2 + 6*x1*x2 + 3*x2^2)
  b <- 30 + (2*x1 - 3*x2)^2 * 
    (18 - 32*x1 + 12*x1^2 + 48*x2 - 36*x1*x2 + 27*x2^2)
  f <- log(a*b)
  f <- (f - m)/s + rnorm(1, sd = 0.1)
  return(f)
 }
```

## Initial sampling and function evaluations

```{r}
# initial samples
N <- 50 
X <- randomLHS(N, 2)
Y <- apply(X, 1, foo)

foo.approx <- km(design = X, response = Y, upper = rep(10, 2),
                 control = list(pop.size = 50, max.generations = 20, 
                                wait.generations = 5, BFGSburnin = 5), 
                 optim.method = "gen")
```

### Optimiztion

```{r, echo=FALSE}
set.seed(1)

nsteps <- 30

res.nsteps <- EGO.nsteps(model = foo.approx, fun = foo,
                         nsteps = nsteps, lower = rep(0, 2), upper = rep(1, 2),
                         parinit = rep(0.5, 2),
                         control = list(pop.size = 50,
                                        max.generations = 20,
                                        wait.generations = 5, BFGSburnin = 5),
                         kmcontrol = NULL)

plot(res.nsteps$value, type = "b", xlab = "Iteration", ylab = "best value")
```

```{r}
## best solution 
res.nsteps$par[which.min(res.nsteps$value), ]
```





